"""
Mission Contract
=================
Defines the structural contract for the Mission object — the root
object of Marketing Brain OS. Every decision in the system starts
from Mission.

Per docs/architecture/MISSION_CONTRACT.md:

Mission MUST contain:
    - Goal
    - User
    - Business
    - Resources
    - Constraints
    - Budget
    - Timeline
    - Current Stage
    - Success Metrics

Mission MUST NOT contain:
    - Research
    - AI Outputs
    - Recommendations
    - Marketing Plans

These are generated by later layers (Research, Strategy, Intelligence)
and must never leak into the Mission object itself. Mission describes
INTENT and CONTEXT, not analysis or output.

No AI. Pure Python.
"""

from typing import Protocol, Any


REQUIRED_FIELDS: list[str] = [
    "goal",
    "user",
    "business",
    "resources",
    "constraints",
    "budget",
    "timeline",
    "current_stage",
    "success_metrics",
]

FORBIDDEN_FIELDS: list[str] = [
    "research",
    "ai_outputs",
    "recommendations",
    "marketing_plans",
]

# Allowed values for the "goal" field — kept intentionally small.
# Extend only through a deliberate contract change, not silently.
VALID_GOALS: list[str] = [
    "sell_existing_product",   # user already has a product/source (e.g. a Telegram channel)
    "affiliate_marketing",     # user sells other people's products for commission
    "build_audience_first",    # user has content but no product/audience yet
]

VALID_EXPERIENCE_LEVELS: list[str] = [
    "beginner",
    "experienced",
]

VALID_SOURCE_TYPES: list[str] = [
    "telegram_channel",
    "facebook_page",
    "instagram_page",
    "tiktok_account",
    "website",
    "none_yet",
]

VALID_SALES_TOOLS: list[str] = [
    "manual_reply",
    "chatbot",
    "payment_link",
    "delivery_company",
    "none_yet",
]


class MissionBuilderProtocol(Protocol):
    """Contract for anything that constructs a Mission from raw onboarding answers."""

    def build(self, answers: dict[str, Any]) -> dict[str, Any]: ...


class MissionValidatorProtocol(Protocol):
    """Contract for anything that validates a Mission object for completeness/correctness."""

    def validate(self, mission: dict[str, Any]) -> "ValidationResultProtocol": ...


class ValidationResultProtocol(Protocol):
    is_valid: bool
    errors: list[str]


class MissionRepositoryProtocol(Protocol):
    """Contract for Mission persistence. Pure storage — no business logic."""

    def save(self, mission: dict[str, Any]) -> dict[str, Any]: ...
    def get_by_id(self, mission_id: str) -> dict[str, Any] | None: ...
    def get_latest(self) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...


class MissionEngineProtocol(Protocol):
    """Contract for the orchestrator that runs the onboarding flow end-to-end."""

    def run_interactive(self) -> dict[str, Any]: ...
    def intake(self, answers: dict[str, Any]) -> dict[str, Any]: ...
